name: vocario
description: "AI Audio Summarizer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  logger: ^2.6.1
  equatable: ^2.0.5
  go_router: ^14.6.2
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0
  flutter_sound: 9.28.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  riverpod_generator: 2.6.5
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

